# Generated by Django 5.0.4 on 2024-05-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketfinder', '0004_trainjourney_pass_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainfare',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='trainfare',
            name='origin',
        ),
        migrations.DeleteModel(
            name='TrainTicket',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='processed',
        ),
        migrations.DeleteModel(
            name='TrainFare',
        ),
    ]
