# Generated by Django 5.0.4 on 2024-05-27 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketfinder', '0005_remove_trainfare_destination_remove_trainfare_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainstation',
            name='location',
        ),
    ]
